version: '2'

volumes:
  moovooca_db:
    driver: local

services:
  moovooca_postgres:
    image: postgres:latest
    container_name: moovooca_postgres
    volumes:
      - moovooca_db:/var/lib/postgres/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
  
  moovooca_server:
    image: python:3.10.11-slim-bullseye
    container_name: moovooca_server
    depends_on:
      - moovooca_postgres
    volumes:
      - ./server:/server
    command: >
      bash -c "cd /server && pip install -r requirements.txt && python3 app.py"
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: 'secret'
      DATABASE_URL: 'postgresql://postgres:postgres@moovooca_postgres:5432'
      FLASK_ENV: 'development'
  
  moovooca_web:
    image: node:latest
    container_name: moovooca_web
    depends_on:
      - moovooca_server
    volumes:
      - ./web:/web
    command: >
      bash -c "cd /web && yarn && yarn dev"
    ports:
      - "3000:3000"
    environment:
      SERVER_API_URL: 'http://moovooca_server:5000'
      NEXT_PUBLIC_API_URL: 'http://192.168.1.9:5000'